'use client';

import { QrCodeIcon } from '@heroicons/react/24/outline';
import { useId, useState } from 'react';

import { describedBy, Field, TextInput } from '@/components/ui/field';
import { FormDialog } from '@/components/ui/form-dialog';
import { boothFormOf, boothSchema, emptyBooth, type Booth, type BoothForm } from '@/lib/passport/passport';
import type { BoothBody } from '@/lib/passport/use-passport';

type Errors = Partial<Record<keyof BoothForm, string>>;

/** Add a stand (its code is generated by the API), or edit one. */
export function BoothDialog({
  open,
  booth,
  pending,
  error,
  onSave,
  onClose,
}: {
  open: boolean;
  booth: Booth | null;
  pending: boolean;
  error: string | null;
  onSave: (body: BoothBody) => void;
  onClose: () => void;
}) {
  const baseId = useId();
  const id = (n: string) => `${baseId}-${n}`;
  const [form, setForm] = useState<BoothForm>(emptyBooth);
  const [errors, setErrors] = useState<Errors>({});
  const [openedFor, setOpenedFor] = useState<Booth | null | undefined>(undefined);
  if (open && openedFor !== booth) {
    setOpenedFor(booth);
    setForm(booth ? boothFormOf(booth) : emptyBooth());
    setErrors({});
  }
  const set = (k: keyof BoothForm, v: string) => {
    setForm((f) => ({ ...f, [k]: v }));
    if (errors[k]) setErrors((e) => ({ ...e, [k]: undefined }));
  };

  return (
    <FormDialog
      open={open}
      icon={QrCodeIcon}
      title={booth ? 'Edit stand' : 'Add stand'}
      subtitle={booth ? `Code ${booth.code} stays the same, so printed signs keep working.` : 'A code for its sign is generated when you add it.'}
      pending={pending}
      submitLabel={booth ? 'Save stand' : 'Add stand'}
      error={error}
      onClose={() => {
        setOpenedFor(undefined);
        onClose();
      }}
      onSubmit={(event) => {
        event.preventDefault();
        const parsed = boothSchema.safeParse(form);
        if (!parsed.success) {
          const next: Errors = {};
          for (const issue of parsed.error.issues) next[issue.path[0] as keyof BoothForm] ??= issue.message;
          setErrors(next);
          return;
        }
        onSave(parsed.data);
      }}
    >
      <Field id={id('name')} label="Stand" error={errors.name}>
        <TextInput id={id('name')} value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="UN Women Nigeria" invalid={!!errors.name} maxLength={120} aria-describedby={describedBy(id('name'), errors.name)} autoFocus />
      </Field>
      <Field id={id('location')} label="Where it is" optional error={errors.location} hint="Helps delegates find it, for example “Exhibition hall, stand 14”.">
        <TextInput id={id('location')} value={form.location} onChange={(e) => set('location', e.target.value)} placeholder="Exhibition hall, stand 14" invalid={!!errors.location} maxLength={120} />
      </Field>
      <Field id={id('description')} label="About the stand" optional error={errors.description}>
        <textarea
          id={id('description')}
          rows={3}
          value={form.description}
          onChange={(e) => set('description', e.target.value)}
          placeholder="What delegates can see or do there."
          maxLength={2000}
          className="w-full resize-none rounded-lg border border-[#bdbdbd] bg-surface px-3 py-2.5 text-sm leading-5 text-ink shadow-xs outline-none transition-shadow placeholder:text-placeholder focus:shadow-[0_1px_2px_rgba(36,36,36,0.05),0_0_0_4px_#f1f1f1]"
        />
      </Field>
    </FormDialog>
  );
}
